### ISSUE TITLE
Use the maybe_do_shortcode function in the edd_items_in_cart shortcode

### ISSUE THREAD

**Issue by Chaddeus** [easydigitaldownloads/edd-additional-shortcodes#10]
Hello @cklosowski , in testing the Additional Shortcodes extension, I found that the items_in_cart shortcode doesn't allow for nested shortcodes.

Reviewing the code, it looks like it doesn't use the maybe_do_shortcode function. Can this shortcode be "fixed" so we can next shortcodes inside?

Thank you!

**Comment by cklosowski** [comment]
Yep. I'll get that fixed up, sorry for the oversight.
