### ISSUE TITLE
Push an update for compatibility with latest WP

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/edd-additional-shortcodes#13]
Issue raised by a custome as WordFence is marking it as abandoned as it has not been updated in a while. Same on the .org repo.
This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

**Comment by robincornett** [comment]
This would be a good opportunity to update the plugin author, etc. as well.
