### ISSUE TITLE
Improve readme formatting -- put shortcode examples in code blocks

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/edd-additional-shortcodes#14]
Right now I find the readme a little hard to read.

![Screenshot from 2021-03-18 14-40-17](https://user-images.githubusercontent.com/6324272/111644583-e1ce5600-87f7-11eb-8e28-9091d758e62f.png)

I think it would be better if the shortcode examples were in code blocks.

**Comment by LisaCee** [comment]
PR #16 Adds code blocks around shortcodes, adds formatting for readability and updates description to use complete sentences.
