### ISSUE TITLE
Update plugin information and source

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-additional-shortcodes#2]
- [x] Update Plugin URI: `https://easydigitaldownloads.com/downloads/edd-additional-shortcodes/` (proposed)
- [x] Update Author: `Easy Digital Downloads`
- [x] Update Author URI: `https://easydigitaldownloads.com`
- [x] Update readme.txt contributors: `easydigitaldownloads, cklosows`
- [x] Upload to EDD site

Check off the list once completed: https://trello.com/c/XWLBRC2o/275-update-authorship-of-edd-plugins

**Comment by cklosowski** [comment]
@SDavisMedia if i'm not mistaken, we don't upload to the EDD stie for these right? we just have to create a page for them? Since we distrubute them based off the URL to the .org .zip file.

**Comment by SDavisMedia** [comment]
@cklosowski Correct, if it's on .org. :+1:
