### ISSUE TITLE
If the cart contains specific products

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-additional-shortcodes#3]
This was mentioned on the product description but I removed it because it's not a feature. Would be a nice one, though.

A shortcode with an `ids` parameter to be used for determining whether or not _specific_ downloads are in the cart.

**Comment by cklosowski** [comment]
new shortcode is `edd_items_in_cart`.

It accepts 2 parameters:
1) `ids` which is a comma separated list of download IDs
2) `match` which supports `any` and `all`. `any` is the default. If `all` is selected but not all IDs are found in the cart, it does not show the content. If `any` is selected, it only takes 1 match for it to return the content.

**Comment by cklosowski** [comment]
Testing Shortcodes:
```
<h3>edd_items_in_cart Single</h3>
[edd_items_in_cart ids="648"]Item is in cart[/edd_items_in_cart]

<h3>edd_items_in_cart Multiple, Any</h3>
[edd_items_in_cart ids="648,662" match="any"]One of the items is in cart[/edd_items_in_cart]

<h3>edd_items_in_cart Multiple, All</h3>
[edd_items_in_cart ids="648,662" match="all"]Alll the items are in cart[/edd_items_in_cart]
```

**Comment by SDavisMedia** [comment]
Works perfectly, Very nice. :+1:
